//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WellboreProfileView.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WellboreProfileView.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ArrayOfPoint3D xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Point3D&gt;
        ///    &lt;X&gt;0&lt;/X&gt;
        ///    &lt;Y&gt;0&lt;/Y&gt;
        ///    &lt;Z&gt;0&lt;/Z&gt;
        ///  &lt;/Point3D&gt;
        ///  &lt;Point3D&gt;
        ///    &lt;X&gt;0&lt;/X&gt;
        ///    &lt;Y&gt;0.10820935772014681&lt;/Y&gt;
        ///    &lt;Z&gt;-19.999609685831309&lt;/Z&gt;
        ///  &lt;/Point3D&gt;
        ///  &lt;Point3D&gt;
        ///    &lt;X&gt;0&lt;/X&gt;
        ///    &lt;Y&gt;0.22776153777548458&lt;/Y&gt;
        ///    &lt;Z&gt;-29.998892878938943&lt;/Z&gt;
        ///  &lt;/Point3D&gt;
        ///  &lt;Point3D&gt;
        ///    &lt;X&gt;0&lt;/X&gt;
        ///    &lt;Y&gt;0.3909422964387359&lt;/Y&gt;
        ///    &lt;Z&gt;-39.997544014106062&lt;/Z&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3DProfilePathPoints_9777_2 {
            get {
                return ResourceManager.GetString("_3DProfilePathPoints_9777_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ArrayOfProfilePathGridViewModel xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;ProfilePathGridViewModel&gt;
        ///    &lt;Id&gt;18805&lt;/Id&gt;
        ///    &lt;WellboreId&gt;0&lt;/WellboreId&gt;
        ///    &lt;VerticalDepth&gt;0&lt;/VerticalDepth&gt;
        ///    &lt;InclinationAngle&gt;0&lt;/InclinationAngle&gt;
        ///    &lt;AzimuthAngle&gt;0&lt;/AzimuthAngle&gt;
        ///    &lt;Extension&gt;0&lt;/Extension&gt;
        ///  &lt;/ProfilePathGridViewModel&gt;
        ///  &lt;ProfilePathGridViewModel&gt;
        ///    &lt;Id&gt;18953&lt;/Id&gt;
        ///    &lt;WellboreId&gt;0&lt;/WellboreId&gt;
        ///    &lt;Vertica [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProfilePathGridViewModel_9777_2 {
            get {
                return ResourceManager.GetString("ProfilePathGridViewModel_9777_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ArrayOfProfilePathPoint xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;ProfilePathPoint&gt;
        ///    &lt;VerticalDepth&gt;20&lt;/VerticalDepth&gt;
        ///    &lt;InclinationAngle&gt;0.3&lt;/InclinationAngle&gt;
        ///    &lt;AzimuthAngle&gt;0&lt;/AzimuthAngle&gt;
        ///    &lt;Extension&gt;0&lt;/Extension&gt;
        ///  &lt;/ProfilePathPoint&gt;
        ///  &lt;ProfilePathPoint&gt;
        ///    &lt;VerticalDepth&gt;40&lt;/VerticalDepth&gt;
        ///    &lt;InclinationAngle&gt;0.36&lt;/InclinationAngle&gt;
        ///    &lt;AzimuthAngle&gt;0&lt;/AzimuthAngle&gt;
        ///    &lt;Extension&gt;0&lt;/Exten [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProfilePathPoints_3472Г_1 {
            get {
                return ResourceManager.GetString("ProfilePathPoints_3472Г_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TrajectoryWellbore {
            get {
                object obj = ResourceManager.GetObject("TrajectoryWellbore", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
