CREATE TABLE WELL
(
   ID bigint NOT NULL IDENTITY (1, 1),
   CONSTRAINT PK_WELL PRIMARY KEY (ID),
   AREA_ID bigint NOT NULL,
   NAME varchar(20) NOT NULL,
   CONSTRAINT UN_WELL_NAME UNIQUE(NAME),
);

ALTER TABLE WELL     
ADD CONSTRAINT FK_WELL_AREA FOREIGN KEY (AREA_ID)     
    REFERENCES AREA (ID)     
    ON DELETE CASCADE    
    ON UPDATE CASCADE  

ALTER TABLE WELL
ADD CONSTRAINT UN_AREA_ID_WELL_NAME  UNIQUE (AREA_ID , NAME);   
GO   