INSERT INTO WELL (AREA_ID, NAME)
     VALUES (1, '1289');
INSERT INTO WELL (AREA_ID, NAME)
     VALUES (1, '2345');
INSERT INTO WELL (AREA_ID, NAME)
     VALUES (1, '3345');
INSERT INTO WELL (AREA_ID, NAME)
     VALUES (2, '983');
INSERT INTO WELL (AREA_ID, NAME)
     VALUES (3, '237');
INSERT INTO WELL (AREA_ID, NAME)
     VALUES (3, '4567');
INSERT INTO WELL (AREA_ID, NAME)
     VALUES (3, '72145');
INSERT INTO WELL (AREA_ID, NAME)
     VALUES (4, '72145ã');
INSERT INTO WELL (AREA_ID, NAME)
     VALUES (4, '6254')
     
GO


