INSERT INTO WELLBORE (WELL_ID, NAME)
     VALUES (1, 'основной');
INSERT INTO WELLBORE ( WELL_ID, NAME)
     VALUES (2, 'основной');
INSERT INTO WELLBORE (WELL_ID, NAME)
     VALUES (3, 'основной');
INSERT INTO WELLBORE (WELL_ID, NAME)
     VALUES (4, 'основной');
INSERT INTO WELLBORE (WELL_ID, NAME)
     VALUES (4, 's2');
INSERT INTO WELLBORE (WELL_ID, NAME)
     VALUES (5, 'основной');
INSERT INTO WELLBORE (WELL_ID, NAME)
     VALUES (6, 'основной');
INSERT INTO WELLBORE (WELL_ID, NAME)
     VALUES (7, 'основной');
     INSERT INTO WELLBORE (WELL_ID, NAME)
     VALUES (7, 's2');
     
GO
