INSERT INTO WELLBORE (WELL_ID, NAME)
     VALUES (1, 'Основной');
INSERT INTO WELLBORE ( WELL_ID, NAME)
     VALUES (2, 'Основной');
INSERT INTO WELLBORE (WELL_ID, NAME)
     VALUES (3, 'Основной');
INSERT INTO WELLBORE (WELL_ID, NAME)
     VALUES (4, 'Основной');
INSERT INTO WELLBORE (WELL_ID, NAME)
     VALUES (4, 's2');
INSERT INTO WELLBORE (WELL_ID, NAME)
     VALUES (5, 'Основной');
INSERT INTO WELLBORE (WELL_ID, NAME)
     VALUES (6, 'Основной');
INSERT INTO WELLBORE (WELL_ID, NAME)
     VALUES (7, 'Основной');
     INSERT INTO WELLBORE (WELL_ID, NAME)
     VALUES (7, 's2');
     
GO
