CREATE TABLE PROFILE_PATH
(
   ID bigint NOT NULL IDENTITY (1, 1),
   CONSTRAINT PK_PROFILE_PATH PRIMARY KEY (ID),
   WELLBORE_ID bigint NOT NULL,
   VERTICAL_DEPTH float NOT NULL,
   INCLINATION_ANGLE float NOT NULL,
   AZIMUTH_ANGLE float NOT NULL,
   EXTENSION float NOT NULL
);

ALTER TABLE PROFILE_PATH     
ADD CONSTRAINT FK_PROFILE_PATH_WELLBORE FOREIGN KEY (WELLBORE_ID)     
    REFERENCES WELLBORE (ID)     
    ON DELETE CASCADE    
    ON UPDATE CASCADE  

